### PR TITLE
Update react-vr demo menu

### PR DESCRIPTION
**Pull request by shaoboyan**
Update react-vr demo

### CODE REVIEW

**Comment by shaoboyan** [comment]
@huningxin PTAL and double check it!

**Comment by huningxin** [comment]
```
diff --git a/og.js b/og.js
index 8a635d1..50a800c 100644
--- a/og.js
+++ b/og.js
@@ -240,7 +240,7 @@ function initScene(player, scene, guiSys) {
         },
         {
           text: "Cylindrical Panel",
-          url: "reactvr/react-vr/dist/CylindricalPanle/index.html",
+          url: "reactvr/react-vr/dist/CylindricalPanel/index.html",^M
           description: "Show a cylindrical panel!",
         },
         {
@@ -250,17 +250,17 @@ function initScene(player, scene, guiSys) {
         },
         {
           text: "Mesh Import",
-          url: "reactvr/recat-vr/dist/ModelSample/index.html",
+          url: "reactvr/react-vr/dist/ModelSample/index.html",^M
           description: "Combine UI Panels and Meshes!",
         },
         {
           text: "Video Scene",
-          url: "reactvr/recat-vr/dist/VideoSample/index.html",
+          url: "reactvr/react-vr/dist/VideoSample/index.html",^M
           description: "Watching Video in a cinema!",
         },
         {
           text: "360 Video",
-          url: "reactvr/recat-vr/dist/VideoSample360/index.html",
+          url: "reactvr/react-vr/dist/VideoSample360/index.html",^M
           description: "Watching 360 video in HMD!",
         },
       ],
```

@shaoboyan , some typos, please fix them. Thanks!

**Comment by shaoboyan** [comment]
@huningxin it seems that Ctrl+M it is because of windows file format.

**Comment by huningxin** [comment]
Correct. Please ignore the Windows line end and fix the typo. Then we merge it. Thanks!

**Comment by huningxin** [comment]
@shaoboyan , any updates?

**Comment by shaoboyan** [comment]
@huningxin Sorry for delay. Update it!

**Comment by huningxin** [comment]
verified! Thank!

**Pull request merged**
